services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng-server
    ports:
      - "514:514/udp"
      - "514:514/tcp"
      - "601:601/tcp"
    volumes:
      - syslog-data:/var/log
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - log-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - log-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - syslog-data:/var/log  # Scrape logs from syslog-ng
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - log-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this in production
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - log-network

networks:
  log-network:
    driver: bridge

volumes:
  syslog-data:
  loki-data:
  grafana-data:
