services:
  syslog-ng:
    image: balabit/syslog-ng:latest  # Official syslog-ng image
    container_name: syslog-ng-server
    ports:
      - "514:514/udp"  # Syslog UDP port
      - "514:514/tcp"  # Syslog TCP port (optional)
      - "601:601/tcp"  # Syslog TCP for reliable delivery (optional)
    volumes:
      - syslog-data:/var/log  # Persistent storage for logs
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf  # Custom config file
    environment:
      - TZ=UTC  # Set timezone as needed
    restart: unless-stopped

volumes:
  syslog-data:
